# Generated by Django 6.0.6 on 2026-09-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Phanie Magic Touch', max_length=100)),
                ('tagline', models.CharField(default='Hair artistry, made unforgettable.', max_length=200)),
                ('hero_title', models.CharField(default='YOUR NEXT LOOK.', max_length=100)),
                ('hero_text', models.CharField(default='Intentional styles, immaculate detail, and a look that stays with you.', max_length=300)),
                ('whatsapp_number', models.CharField(default='237000000000', max_length=30)),
                ('address', models.CharField(default='Your studio address, Douala, Cameroon', max_length=200)),
                ('hours', models.JSONField(default=list, help_text='Each entry appears on its own line, e.g. ["Tue – Sat · 9:00 AM – 6:00 PM", "Sunday · By appointment"]')),
                ('directions_url', models.URLField(default='https://www.google.com/maps')),
                ('instagram_url', models.URLField(default='https://instagram.com')),
            ],
            options={
                'verbose_name': 'Business profile',
                'verbose_name_plural': 'Business profiles',
            },
        ),
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('Braids', 'Braids'), ('Locs', 'Locs'), ('Twists', 'Twists'), ('Wigs', 'Wigs'), ('Natural Hair', 'Natural Hair'), ('Other', 'Other')], max_length=30)),
                ('caption', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', help_text='External image URL (e.g. Unsplash).')),
                ('image', models.ImageField(blank=True, help_text='Optional: upload a local image. Falls back to image_url.', null=True, upload_to='styles/')),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hairstyle',
                'verbose_name_plural': 'Hairstyles',
                'ordering': ['-featured', '-created_at', 'title'],
            },
        ),
    ]
