# Generated by Django 6.0.6 on 2026-09-19 19:29

from django.db import migrations


image = lambda id: f"https://images.unsplash.com/{id}?auto=format&fit=crop&w=1400&q=85"


def seed_sample_data(apps, schema_editor):
    BusinessProfile = apps.get_model("studio", "BusinessProfile")
    Hairstyle = apps.get_model("studio", "Hairstyle")

    BusinessProfile.objects.get_or_create(
        name="Phanie Magic Touch",
        defaults={
            "tagline": "Hair artistry, made unforgettable.",
            "hero_title": "YOUR NEXT LOOK.",
            "hero_text": "Intentional styles, immaculate detail, and a look that stays with you.",
            "whatsapp_number": "237000000000",
            "address": "Your studio address, Douala, Cameroon",
            "hours": ["Tue – Sat · 9:00 AM – 6:00 PM", "Sunday · By appointment"],
            "directions_url": "https://www.google.com/maps",
            "instagram_url": "https://instagram.com",
        },
    )

    styles = [
        ("Sculpted Knotless Braids", "sculpted-knotless-braids", "Braids", "Lightweight, precise and effortlessly elegant.", "photo-1522337360788-8b13dee7a37e", True),
        ("Soft Glam Waves", "soft-glam-waves", "Wigs", "A polished finish with movement.", "photo-1512496015851-a90fb38ba796", True),
        ("Crown Loc Style", "crown-loc-style", "Locs", "Defined texture, finished with care.", "photo-1549236177-f9b00317542b", True),
        ("Defined Natural Curls", "defined-natural-curls", "Natural Hair", "Healthy hair, elevated texture.", "photo-1525507119028-ed4c629a60a3", False),
        ("Signature Senegalese Twists", "signature-senegalese-twists", "Twists", "A timeless protective style.", "photo-1508182311256-e3f7d0e5f1e2", False),
        ("Editorial Updo", "editorial-updo", "Other", "For the moments that deserve drama.", "photo-1487412720507-e7ab37603c6f", False),
    ]
    for title, slug, category, caption, image_id, featured in styles:
        Hairstyle.objects.get_or_create(
            slug=slug,
            defaults={
                "title": title,
                "category": category,
                "caption": caption,
                "image_url": image(image_id),
                "published": True,
                "featured": featured,
            },
        )


def unseed_sample_data(apps, schema_editor):
    BusinessProfile = apps.get_model("studio", "BusinessProfile")
    Hairstyle = apps.get_model("studio", "Hairstyle")
    Hairstyle.objects.filter(slug="sculpted-knotless-braids").delete()
    Hairstyle.objects.filter(slug="soft-glam-waves").delete()
    Hairstyle.objects.filter(slug="crown-loc-style").delete()
    Hairstyle.objects.filter(slug="defined-natural-curls").delete()
    Hairstyle.objects.filter(slug="signature-senegalese-twists").delete()
    Hairstyle.objects.filter(slug="editorial-updo").delete()
    BusinessProfile.objects.filter(name="Phanie Magic Touch").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_sample_data, unseed_sample_data),
    ]